Readium.Models.BookExtractorBase=Backbone.Model.extend({MIMETYPE:"mimetype",CONTAINER:"META-INF/container.xml",EPUB3_MIMETYPE:"application/epub+zip",DISPLAY_OPTIONS:"META-INF/com.apple.ibooks.display-options.xml",defaults:{task_size:100,progress:1,extracting:!1,log_message:"Fetching epub file"},clean:function(){this.removeHandlers();this.fsApi&&this.fsApi.rmdir(this.base_dir_name)},parseContainerRoot:function(a){var b=this.get("root_file_path");this.packageDoc=new Readium.Models.ValidatedPackageMetaData({key:this.base_dir_name,
src_url:this.get("src"),file_path:this.base_dir_name+"/"+b,root_url:this.get("root_url")+"/"+b});this.packageDoc.reset(a);this.trigger("parsed:root_file")},writeFile:function(a,b,c){var d=this;this.fsApi.writeFile(this.base_dir_name+"/"+a,b,c,function(){d.set("error","ERROR: while writing to filesystem")})},parseMetaInfo:function(a){a=(new window.DOMParser).parseFromString(a,"text/xml").getElementsByTagName("rootfile");a.length<1?this.set("error","This epub is not valid. The rootfile could not be located."):
a[0].hasAttribute("full-path")?this.set("root_file_path",a[0].attributes["full-path"].value):this.set("error","Error: could not find package rootfile")},validateMimetype:function(a){$.trim(a)===this.EPUB3_MIMETYPE?this.trigger("validated:mime"):this.set("error","Invalid mimetype discovered. Progress cancelled.")},removeHandlers:function(){this.off()},extraction_complete:function(){this.set("extracting",!1)},finish_extraction:function(){var a=this;this.set("log_message","Unpacking process completed successfully!");
this.packageDoc.save({},{success:function(){a.trigger("extraction_success")},failure:function(){a.set("failure","ERROR: unknown problem during unpacking process")}})},correctURIs:function(){var a=this.get("root_url"),b=this.get("patch_position"),c=this.get("manifest"),d=this.packageDoc.get("id"),e=this;b>=c.length?(this.off("change:patch_position"),this.finish_extraction()):(this.set("log_message","monkey patching: "+c[b]),monkeyPatchUrls(a+"/"+c[b],function(){e.incPatchPos()},function(){e.set("failure",
"ERROR: unknown problem during unpacking process")},d))},incPatchPos:function(){var a=this.get("patch_position")||0;a+=1;this.set("patch_position",a)}});
Readium.Models.ZipBookExtractor=Readium.Models.BookExtractorBase.extend({initialize:function(){zip.workerScriptsPath="../lib/";var a=this.get("src_filename");if(this.get("file"))this.base_dir_name=Readium.Utils.MD5(a+(new Date).toString()),this.set("src",a);else throw"A zip file must be specified";},extractEntryByName:function(a,b){var c,d;if(d=_.find(this.entries,function(b){return b.filename===a}))c=new zip.TextWriter,d.getData(c,b);else throw"asked to extract non-existent zip-entry: "+a;},extractContainerRoot:function(){var a=
this,b=this.get("root_file_path");try{this.extractEntryByName(b,function(b){a.parseContainerRoot(b)})}catch(c){this.set("error",c)}},extractMetaInfo:function(){var a=this;try{this.extractEntryByName(this.CONTAINER,function(b){a.parseMetaInfo(b)})}catch(b){this.set("error",b)}},extractMimetype:function(){var a=this;this.set("log_message","Verifying mimetype");try{this.extractEntryByName(this.MIMETYPE,function(b){a.validateMimetype(b)})}catch(b){this.set("error",b)}},validateZip:function(){var a=this;
this.set("log_message","Validating zip file");var b=_.any(this.entries,function(b){return b.filename===a.MIMETYPE}),c=_.any(this.entries,function(b){return b.filename===a.CONTAINER});b&&c?this.trigger("validated:zip"):this.set("error","File does not appear to be a valid EPUB. Progress cancelled.")},extractEntry:function(a){var b=this,c=new zip.BlobWriter;a.getData(c,function(c){b.writeFile(a.filename,c,function(){b.available_workers+=1;b.set("zip_position",b.get("zip_position")+1)})})},extractBook:function(){var a;
if(this.get("zip_position")===0)this.available_workers=5,this.entry_position=0,this.on("change:zip_position",this.checkCompletion,this);for(;this.available_workers>0&&this.entry_position<this.entries.length;)a=this.entries[this.entry_position],a.filename.substr(-1)==="/"?(this.entry_position+=1,this.set("zip_position",this.get("zip_position")+1)):(this.available_workers-=1,this.entry_position+=1,this.extractEntry(a));for(a=0;a<this.entries.length;a++);},parseIbooksDisplayOptions:function(){var a=
this;try{this.extractEntryByName(this.DISPLAY_OPTIONS,function(b){a.packageDoc.parseIbooksDisplayOptions(b);a.trigger("parsed:ibooks_options")})}catch(b){this.trigger("parsed:ibooks_options")}},checkCompletion:function(){var a=this.get("zip_position");a===this.entries.length?(this.set("log_message","All files unzipped successfully!"),this.set("patch_position",0)):this.set("log_message","extracting: "+this.entries[a].filename)},beginUnpacking:function(){for(var a=[],b,c=0;c<this.entries.length;c++)b=
this.entries[c],b.filename.substr(-1)!=="/"&&a.push(b.name);this.set("manifest",a);this.set("zip_position",0)},extract:function(){this.on("initialized:zip",this.validateZip,this);this.on("validated:zip",this.extractMimetype,this);this.on("validated:mime",this.extractMetaInfo,this);this.on("change:root_file_path",this.extractContainerRoot,this);this.on("parsed:root_file",this.parseIbooksDisplayOptions,this);this.on("parsed:ibooks_options",this.beginUnpacking,this);this.on("change:zip_position",this.extractBook,
this);this.on("change:patch_position",this.correctURIs,this);this.on("change:failure",this.clean,this);this.on("change:failure",this.removeHandlers,this);this.on("change:task_size",this.update_progress,this);this.on("change:zip_position",this.update_progress,this);this.on("change:patch_position",this.update_progress,this);this.on("extraction_success",this.extraction_complete,this);this.set("extracting",!0);var a=this;Readium.FileSystemApi(function(b){a.fsApi=b;a.initializeZip()})},update_progress:function(){var a=
this.get("zip_position")||0,b=this.get("patch_position")||0;this.set("progress",Math.floor((a+b+3)*100/this.get("task_size")))},initializeZip:function(){var a=this;this.fsApi.getFileSystem().root.getDirectory(this.base_dir_name,{create:!0},function(b){a.set("root_url",b.toURL());zip.createReader(new zip.BlobReader(a.get("file")),function(b){b.getEntries(function(b){a.entries=b;a.set("task_size",b.length*2+3);a.trigger("initialized:zip")})},function(){a.set("error","File does not appear to be a valid EPUB. Progress cancelled.")})},
function(){console.log("In beginUnpacking error handler. Does the root dir already exist?")})}});
Readium.Models.UnpackedBookExtractor=Readium.Models.BookExtractorBase.extend({initialize:function(){var a=this.get("dir_picker"),b=[],c;this.fNameStartInd=a.files[0].webkitRelativePath.indexOf("/")+1;this.base_dir_name=Readium.Utils.MD5("Banana"+(new Date).toString());this.fileList=a.files;for(a=0;c=this.fileList[a];++a)c=c.webkitRelativePath,c.substr(-2)!=="/."&&b.push(this.getShortName(c));this.set("src","Local Directory: "+this.fileList[0].webkitRelativePath.substring(0,this.fNameStartInd));this.set("task_size",
b.length*2+3);this.set("manifest",b)},getShortName:function(a){return a.substr(this.fNameStartInd)},update_progress:function(){var a=this.get("write_position")||0,b=this.get("patch_position")||0;this.set("progress",3+a+b)},extract:function(){this.on("validated:dir",this.readMime,this);this.on("validated:mime",this.readMetaInfo,this);this.on("change:root_file_path",this.readContainerRoot,this);this.on("parsed:root_file",this.parseIbooksDisplayOptions,this);this.on("parsed:ibooks_options",this.beginWriting,
this);this.on("change:write_position",this.writeEntry,this);this.on("change:patch_position",this.correctURIs,this);this.on("change:failure",this.clean,this);this.on("change:failure",this.removeHandlers,this);this.on("change:task_size",this.update_progress,this);this.on("change:write_position",this.update_progress,this);this.on("change:patch_position",this.update_progress,this);this.on("extraction_success",this.extraction_complete,this);this.set("extracting",!0);var a=this;Readium.FileSystemApi(function(b){a.fsApi=
b;b.getFileSystem().root.getDirectory(a.base_dir_name,{create:!0},function(b){a.set("root_url",b.toURL());a.validateDir()})})},parseIbooksDisplayOptions:function(){this.trigger("parsed:ibooks_options");var a=this;try{this.readEntryByShortName(this.DISPLAY_OPTIONS,function(b){a.packageDoc.parseIbooksDisplayOptions(b);a.trigger("parsed:ibooks_options")})}catch(b){this.trigger("parsed:ibooks_options")}},validateDir:function(){var a=this.get("manifest");a.indexOf(this.MIMETYPE)>=0&&a.indexOf(this.CONTAINER)>=
0?this.trigger("validated:dir"):this.set("error","the directory you selected was not valid")},readMime:function(){var a=this;this.set("log_message","Verifying mimetype");try{this.readEntryByShortName(this.MIMETYPE,function(b){a.validateMimetype(b)})}catch(b){this.set("error",b)}},readMetaInfo:function(){var a=this;try{this.readEntryByShortName(this.CONTAINER,function(b){a.parseMetaInfo(b)})}catch(b){this.set("error",b)}},readContainerRoot:function(){var a=this,b=this.get("root_file_path");try{this.readEntryByShortName(b,
function(b){a.parseContainerRoot(b)})}catch(c){this.set("error",c)}},beginWriting:function(){this.set("write_position",0)},writeEntry:function(){var a=this,b=this.get("write_position");if(b===this.fileList.length)this.set("patch_position",0);else{var c=this.fileList[b],d=this.getShortName(c.webkitRelativePath);this.set("log_message","writing: "+d);d.substr(-2)==="/."?this.set("write_position",b+1):this.writeFile(d,c,function(){a.set("write_position",b+1)})}},readEntryByShortName:function(a,b){for(var c=
!1,d=this.get("dir_picker").files,e=0;e<d.length;e++)if(this.getShortName(d[e].webkitRelativePath)===a){var c=!0,f=new FileReader;f.onload=function(a){b(a.target.result)};f.readAsText(d[e]);break}if(!c)throw"asked to read non-existent file: "+a;}});
