(function(){var h=Handlebars.template,i=Handlebars.templates=Handlebars.templates||{};i.binding_template=h(function(){return'<iframe scrolling="no" \n\t\tframeborder="0" \n\t\tmarginwidth="0" \n\t\tmarginheight="0" \n\t\twidth="100%" \n\t\theight="100%" \n\t\tclass=\'binding-sandbox\'>\n</iframe>'});i.extracting_item_template=h(function(e,c,d){var d=d||e.helpers,e="",a,b=d.helperMissing,f=this.escapeExpression;e+="<h5>";a=(a=d.log_message)||c.log_message;typeof a==="function"?a=a.call(c,{hash:{}}):
a===void 0&&(a=b.call(c,"log_message",{hash:{}}));e+=f(a)+'</h5>\n<div class="progress progress-striped progress-success active ">\t\n\t\t<div role="status" aria-live="assertive" aria-relevant="all" class="bar" style="width: ';a=(a=d.progress)||c.progress;typeof a==="function"?a=a.call(c,{hash:{}}):a===void 0&&(a=b.call(c,"progress",{hash:{}}));e+=f(a)+'%;"></div>\n</div>';return e});i.fixed_page_template=h(function(e,c,d){var d=d||e.helpers,e="",a,b=d.helperMissing,f=this.escapeExpression;e+='<div class="fixed-page-margin">\n\t<iframe scrolling="no" \n\t\t\tframeborder="0" \n\t\t\tmarginwidth="0" \n\t\t\tmarginheight="0" \n\t\t\twidth="';
a=(a=d.width)||c.width;typeof a==="function"?a=a.call(c,{hash:{}}):a===void 0&&(a=b.call(c,"width",{hash:{}}));e+=f(a)+'px" \n\t\t\theight="';a=(a=d.height)||c.height;typeof a==="function"?a=a.call(c,{hash:{}}):a===void 0&&(a=b.call(c,"height",{hash:{}}));e+=f(a)+'px" \n\t\t\tsrc="';a=(a=d.uri)||c.uri;typeof a==="function"?a=a.call(c,{hash:{}}):a===void 0&&(a=b.call(c,"uri",{hash:{}}));e+=f(a)+"\"\n\t\t\tclass='content-sandbox'>\n\t</iframe>\n</div>";return e});i.image_page_template=h(function(e,
c,d){var d=d||e.helpers,e="",a=d.helperMissing,b=this.escapeExpression;e+='<div class="fixed-page-margin">\n\t<img src="';d=d.uri||c.uri;typeof d==="function"?d=d.call(c,{hash:{}}):d===void 0&&(d=a.call(c,"uri",{hash:{}}));e+=b(d)+'" >\n</div>';return e});i.library_item_template=h(function(e,c,d){var d=d||e.helpers,e="",a,b,f=d.helperMissing,g=this.escapeExpression;e+="<div class='info-wrap clearfix'>\n\t<div class='caption book-info'>\n\t\t<h2 class='green info-item title'>";a=(b=d.data)||c.data;
a=a===null||a===void 0||a===!1?a:a.title;typeof a==="function"?a=a.call(c,{hash:{}}):a===void 0&&(a=f.call(c,"data.title",{hash:{}}));e+=g(a)+"</h2>\n\t\t<div class='info-item author'>";a=(b=d.data)||c.data;a=a===null||a===void 0||a===!1?a:a.author;b=(b=d.orUnknown)||c.orUnknown;a=typeof b==="function"?b.call(c,a,{hash:{}}):b===void 0?f.call(c,"orUnknown",a,{hash:{}}):b;e+=g(a)+"</div>\n\t\t<div class='info-item epub-version'>ePUB ";a=(b=d.data)||c.data;a=a===null||a===void 0||a===!1?a:a.epub_version;
b=(b=d.orUnknown)||c.orUnknown;a=typeof b==="function"?b.call(c,a,{hash:{}}):b===void 0?f.call(c,"orUnknown",a,{hash:{}}):b;e+=g(a)+"</div>\n\t\t\n\t</div>\n\t\n\t<img class='cover-image read' src='";a=(b=d.data)||c.data;a=a===null||a===void 0||a===!1?a:a.cover_href;typeof a==="function"?a=a.call(c,{hash:{}}):a===void 0&&(a=f.call(c,"data.cover_href",{hash:{}}));e+=g(a)+"' width='150' height='220' alt='Open ePUB ";a=(b=d.data)||c.data;a=a===null||a===void 0||a===!1?a:a.title;typeof a==="function"?
a=a.call(c,{hash:{}}):a===void 0&&(a=f.call(c,"data.title",{hash:{}}));e+=g(a)+"'>\n\t\n\t<a href=\"#details-modal-";a=(b=d.data)||c.data;a=a===null||a===void 0||a===!1?a:a.key;typeof a==="function"?a=a.call(c,{hash:{}}):a===void 0&&(a=f.call(c,"data.key",{hash:{}}));e+=g(a)+'" class="info-icon" data-toggle="modal" role="button">\n\t\t<img class=\'info-icon pull-right\' src=\'/images/library/info-icon.png\' height="39px" width="39px" alt=\'';a=(b=d.data)||c.data;a=a===null||a===void 0||a===!1?a:a.title;
typeof a==="function"?a=a.call(c,{hash:{}}):a===void 0&&(a=f.call(c,"data.title",{hash:{}}));e+=g(a)+' information\'>\n\t</a>\n</div>\n\n<div class="caption clearfix buttons">\n\t<a href="#todo" class="btn read" data-book=\'';a=(b=d.data)||c.data;a=a===null||a===void 0||a===!1?a:a.key;typeof a==="function"?a=a.call(c,{hash:{}}):a===void 0&&(a=f.call(c,"data.key",{hash:{}}));e+=g(a)+"' role='button'>";a="i18n_read";b=(b=d.fetchInzMessage)||c.fetchInzMessage;a=typeof b==="function"?b.call(c,a,{hash:{}}):
b===void 0?f.call(c,"fetchInzMessage",a,{hash:{}}):b;e+=g(a)+'</a>\n\t<a href="#details-modal-';a=(b=d.data)||c.data;a=a===null||a===void 0||a===!1?a:a.key;typeof a==="function"?a=a.call(c,{hash:{}}):a===void 0&&(a=f.call(c,"data.key",{hash:{}}));e+=g(a)+'" class="btn details" data-toggle="modal" role="button">\n\t\t';a="i18n_details";b=(b=d.fetchInzMessage)||c.fetchInzMessage;a=typeof b==="function"?b.call(c,a,{hash:{}}):b===void 0?f.call(c,"fetchInzMessage",a,{hash:{}}):b;e+=g(a)+"\n\t</a>\n</div>\n\n<div id='details-modal-";
a=(b=d.data)||c.data;a=a===null||a===void 0||a===!1?a:a.key;typeof a==="function"?a=a.call(c,{hash:{}}):a===void 0&&(a=f.call(c,"data.key",{hash:{}}));e+=g(a)+"' class='modal fade details-modal'>\n\t<div class=\"pull-left modal-cover-wrap\">\n\t\t<img class='details-cover-image' src='";a=(b=d.data)||c.data;a=a===null||a===void 0||a===!1?a:a.cover_href;typeof a==="function"?a=a.call(c,{hash:{}}):a===void 0&&(a=f.call(c,"data.cover_href",{hash:{}}));e+=g(a)+"' width='150' height='220' alt='ePUB cover'>\n\t\t<div class=\"caption clearfix modal-buttons\">\n\t\t\t<a href=\"#\" class=\"btn read\" data-book='<%= data.key %>' role='button'>";
a="i18n_read";b=(b=d.fetchInzMessage)||c.fetchInzMessage;a=typeof b==="function"?b.call(c,a,{hash:{}}):b===void 0?f.call(c,"fetchInzMessage",a,{hash:{}}):b;e+=g(a)+"</a>\n\t\t\t<a class=\"btn btn-danger delete pull-right\" role='button'>";a="i18n_delete";b=(b=d.fetchInzMessage)||c.fetchInzMessage;a=typeof b==="function"?b.call(c,a,{hash:{}}):b===void 0?f.call(c,"fetchInzMessage",a,{hash:{}}):b;e+=g(a)+"</a>\n\t\t</div>\n\t</div>\n\t<div class='caption modal-book-info'>\n\t\t<h3 class='green modal-title'>";
a=(b=d.data)||c.data;a=a===null||a===void 0||a===!1?a:a.title;typeof a==="function"?a=a.call(c,{hash:{}}):a===void 0&&(a=f.call(c,"data.title",{hash:{}}));e+=g(a)+"</h3>\n\t\t<div class='modal-detail gap'>";a="i18n_author";b=(b=d.fetchInzMessage)||c.fetchInzMessage;a=typeof b==="function"?b.call(c,a,{hash:{}}):b===void 0?f.call(c,"fetchInzMessage",a,{hash:{}}):b;e+=g(a);a=(b=d.data)||c.data;a=a===null||a===void 0||a===!1?a:a.author;b=(b=d.orUnknown)||c.orUnknown;a=typeof b==="function"?b.call(c,a,
{hash:{}}):b===void 0?f.call(c,"orUnknown",a,{hash:{}}):b;e+=g(a)+"</div>\n\t\t<div class='modal-detail'>";a="i18n_publisher";b=(b=d.fetchInzMessage)||c.fetchInzMessage;a=typeof b==="function"?b.call(c,a,{hash:{}}):b===void 0?f.call(c,"fetchInzMessage",a,{hash:{}}):b;e+=g(a);a=(b=d.data)||c.data;a=a===null||a===void 0||a===!1?a:a.publisher;b=(b=d.orUnknown)||c.orUnknown;a=typeof b==="function"?b.call(c,a,{hash:{}}):b===void 0?f.call(c,"orUnknown",a,{hash:{}}):b;e+=g(a)+"</div>\n\t\t<div class='modal-detail'>";
a="i18n_pub_date";b=(b=d.fetchInzMessage)||c.fetchInzMessage;a=typeof b==="function"?b.call(c,a,{hash:{}}):b===void 0?f.call(c,"fetchInzMessage",a,{hash:{}}):b;e+=g(a);a=(b=d.data)||c.data;a=a===null||a===void 0||a===!1?a:a.pubdate;b=(b=d.orUnknown)||c.orUnknown;a=typeof b==="function"?b.call(c,a,{hash:{}}):b===void 0?f.call(c,"orUnknown",a,{hash:{}}):b;e+=g(a)+"</div>\n\t\t<div class='modal-detail'>";a="i18n_modified_date";b=(b=d.fetchInzMessage)||c.fetchInzMessage;a=typeof b==="function"?b.call(c,
a,{hash:{}}):b===void 0?f.call(c,"fetchInzMessage",a,{hash:{}}):b;e+=g(a);a=(b=d.data)||c.data;a=a===null||a===void 0||a===!1?a:a.modified_date;b=(b=d.orUnknown)||c.orUnknown;a=typeof b==="function"?b.call(c,a,{hash:{}}):b===void 0?f.call(c,"orUnknown",a,{hash:{}}):b;e+=g(a)+"</div>\n\t\t<div class='modal-detail gap'>";a="i18n_id";b=(b=d.fetchInzMessage)||c.fetchInzMessage;a=typeof b==="function"?b.call(c,a,{hash:{}}):b===void 0?f.call(c,"fetchInzMessage",a,{hash:{}}):b;e+=g(a);a=(b=d.data)||c.data;
a=a===null||a===void 0||a===!1?a:a.id;b=(b=d.orUnknown)||c.orUnknown;a=typeof b==="function"?b.call(c,a,{hash:{}}):b===void 0?f.call(c,"orUnknown",a,{hash:{}}):b;e+=g(a)+"</div>\n\t\t<div class='modal-detail green'>";a="i18n_epub_version";b=(b=d.fetchInzMessage)||c.fetchInzMessage;a=typeof b==="function"?b.call(c,a,{hash:{}}):b===void 0?f.call(c,"fetchInzMessage",a,{hash:{}}):b;e+=g(a);a=(b=d.data)||c.data;a=a===null||a===void 0||a===!1?a:a.epub_version;b=(b=d.orUnknown)||c.orUnknown;a=typeof b===
"function"?b.call(c,a,{hash:{}}):b===void 0?f.call(c,"orUnknown",a,{hash:{}}):b;e+=g(a)+"</div>\n\t\t<div class='modal-detail'>";a="i18n_created_at";b=(b=d.fetchInzMessage)||c.fetchInzMessage;a=typeof b==="function"?b.call(c,a,{hash:{}}):b===void 0?f.call(c,"fetchInzMessage",a,{hash:{}}):b;e+=g(a);a=(b=d.data)||c.data;a=a===null||a===void 0||a===!1?a:a.created_at;b=(b=d.orUnknown)||c.orUnknown;a=typeof b==="function"?b.call(c,a,{hash:{}}):b===void 0?f.call(c,"orUnknown",a,{hash:{}}):b;e+=g(a)+"</div>\n\t</div>\n\t<div class='modal-detail source'>\n\t<span class='green' style=\"padding-right: 10px\">";
a="i18n_source";b=(b=d.fetchInzMessage)||c.fetchInzMessage;a=typeof b==="function"?b.call(c,a,{hash:{}}):b===void 0?f.call(c,"fetchInzMessage",a,{hash:{}}):b;e+=g(a)+"</span>\n\t\t";a=(b=d.data)||c.data;a=a===null||a===void 0||a===!1?a:a.src_url;b=(b=d.orUnknown)||c.orUnknown;a=typeof b==="function"?b.call(c,a,{hash:{}}):b===void 0?f.call(c,"orUnknown",a,{hash:{}}):b;e+=g(a)+"\n\t</div>\n</div>\t\t\t";return e});i.library_items_template=h(function(e,c,d){var d=d||e.helpers,e="",a,b=d.helperMissing,
f=this.escapeExpression;e+="<div id='empty-message'>\n\t<p id='empty-message-text' class='green'>\n\t\t";a="i18n_add_items";d=d.fetchInzMessage||c.fetchInzMessage;a=typeof d==="function"?d.call(c,a,{hash:{}}):d===void 0?b.call(c,"fetchInzMessage",a,{hash:{}}):d;e+=f(a)+"\n\t</p>\n\t<img id='empty-arrow' src='/images/library/empty_library_arrow.png' alt='' />\n</div>";return e});i.ncx_nav_template=h(function(e,c,d){var d=d||e.helpers,e="",a,b=d.helperMissing,f=this.escapeExpression;e+='<li class="nav-elem">\n\t<a href="';
a=(a=d.href)||c.href;typeof a==="function"?a=a.call(c,{hash:{}}):a===void 0&&(a=b.call(c,"href",{hash:{}}));e+=f(a)+'">';a=(a=d.text)||c.text;typeof a==="function"?a=a.call(c,{hash:{}}):a===void 0&&(a=b.call(c,"text",{hash:{}}));e+=f(a)+"</a>\n</li>";return e});i.reflowing_template=h(function(e,c,d){var d=d||e.helpers,e="",a=d.helperMissing,b=this.escapeExpression;e+='<div id="flowing-wrapper">\n\t<iframe scrolling="no" \n\t\t\tframeborder="0" \n\t\t\tmarginwidth="0" \n\t\t\tmarginheight="0" \n\t\t\twidth="50%" \n\t\t\theight="100%" \n\t\t\tsrc="';
d=d.uri||c.uri;typeof d==="function"?d=d.call(c,{hash:{}}):d===void 0&&(d=a.call(c,"uri",{hash:{}}));e+=b(d)+'"\n\t\t\tid="readium-flowing-content">\n\t</iframe>\n</div>';return e});i.scrolling_page_template=h(function(e,c,d){var d=d||e.helpers,e="",a=d.helperMissing,b=this.escapeExpression;e+='<div id="scrolling-content" class="scrolling-page-wrap">\n\t<div class="scrolling-page-margin">\n\n\t\t<iframe scrolling="yes" \n\t\t\t\tframeborder="0" \n\t\t\t\tmarginwidth="0" \n\t\t\t\tmarginheight="0" \n\t\t\t\twidth="100%" \n\t\t\t\theight="100%" \n\t\t\t\tsrc="';
d=d.uri||c.uri;typeof d==="function"?d=d.call(c,{hash:{}}):d===void 0&&(d=a.call(c,"uri",{hash:{}}));e+=b(d)+"\"\n\t\t\t\tclass='content-sandbox'>\n\t\t</iframe>\n\t</div>\n</div>";return e})})();
