Readium.Models.PackageDocumentParser=function(a){this.uri_obj=a};
Readium.Models.PackageDocumentParser.JathTemplate={metadata:{id:"//def:metadata/dc:identifier",epub_version:"//def:package/@version",title:"//def:metadata/dc:title",author:"//def:metadata/dc:creator",publisher:"//def:metadata/dc:publisher",description:"//def:metadata/dc:description",rights:"//def:metadata/dc:rights",language:"//def:metadata/dc:language",pubdate:"//def:metadata/dc:date",modified_date:"//def:metadata/def:meta[@property='dcterms:modified']",layout:"//def:metadata/def:meta[@property='rendition:layout']",
spread:"//def:metadata/def:meta[@property='rendition:spread']",orientation:"//def:metadata/def:meta[@property='rendition:orientation']",ncx:"//def:spine/@toc",page_prog_dir:"//def:spine/@page-progression-direction",active_class:"//def:metadata/def:meta[@property='media:active-class']"},manifest:["//def:item",{id:"@id",href:"@href",media_type:"@media-type",properties:"@properties",media_overlay:"@media-overlay"}],spine:["//def:itemref",{idref:"@idref",properties:"@properties",linear:"@linear"}],bindings:["//def:bindings/def:mediaType",
{handler:"@handler",media_type:"@media-type"}]};
Readium.Models.PackageDocumentParser.prototype.parse=function(a){var c;c=typeof a==="string"?(new window.DOMParser).parseFromString(a,"text/xml"):a;Jath.resolver=function(a){return{def:"http://www.idpf.org/2007/opf",dc:"http://purl.org/dc/elements/1.1/"}[a]};a=Jath.parse(Readium.Models.PackageDocumentParser.JathTemplate,c);a.paginate_backwards=this.paginateBackwards(c);if(c=this.getCoverHref(c))a.metadata.cover_href=this.resolveUri(c);if(a.metadata.layout==="pre-paginated")a.metadata.fixed_layout=
!0;a.manifest=new Readium.Collections.ManifestItems(a.manifest,{packageDocument:this});a.mo_map=this.resolveMediaOverlays(a.manifest);a.spine=this.parseSpineProperties(a.spine);return a};
Readium.Models.PackageDocumentParser.prototype.getCoverHref=function(a){var c,b;c=a.getElementsByTagName("manifest")[0];b=$('item[properties~="cover-image"]',c);if(b.length===1&&b.attr("href"))return b.attr("href");a=$('meta[name="cover"]',a);b=a.attr("content");if(a.length===1&&b&&(b=$('item[id="'+b+'"]',c),b.length===1&&b.attr("href")))return b.attr("href");b=$("#cover",c);return b.length===1&&b.attr("href")?b.attr("href"):null};
Readium.Models.PackageDocumentParser.prototype.parseSpineProperties=function(a){for(var c=function(a){for(var b={},a=a.split(" "),c=0;c<a.length;c++){if(a[c]==="rendition:page-spread-center")b.page_spread="center";if(a[c]==="page-spread-left")b.page_spread="left";if(a[c]==="page-spread-right")b.page_spread="right";if(a[c]==="page-spread-right")b.page_spread="right";if(a[c]==="rendition:layout-reflowable")b.fixed_flow=!1;if(a[c]==="rendition:layout-pre-paginated")b.fixed_flow=!0}return b},b=0;b<a.length;b++){var e=
c(a[b].properties);_.extend(a[b],e)}return a};Readium.Models.PackageDocumentParser.prototype.resolveMediaOverlays=function(a){var c=this,b={};a.forEach(function(a){if(a.get("media_type")==="application/smil+xml"){var d=c.resolveUri(a.get("href")),f=new Readium.Models.MediaOverlay;f.setUrl(d);f.fetch();b[a.id]=f}});return b};Readium.Models.PackageDocumentParser.prototype.paginateBackwards=function(a){return $("spine",a).attr("page-progression-direction")==="ltr"};
Readium.Models.PackageDocumentParser.prototype.crunchSpine=function(a,c){var b=this,e=-1,d=_.map(a,function(a){e+=1;var d=c.find(function(b){if(b.get("id")===a.idref)return b}),g=b.get("book");return _.extend({},a,d.attributes,{spine_index:e},{page_prog_dir:g.get("page_prog_dir")})});return new Readium.Collections.Spine(d,{packageDocument:this})};Readium.Models.PackageDocumentParser.prototype.resolveUri=function(a){uri=new URI(a);return uri.resolve(this.uri_obj).toString()};
