Readium.Views.ReflowablePaginationView=Readium.Views.PaginationViewBase.extend({initialize:function(a){Readium.Views.PaginationViewBase.prototype.initialize.call(this,a);this.page_template=Handlebars.templates.reflowing_template;this.stashModernizrPrefixedProps();this.offset_dir=this.model.epub.get("page_prog_dir")==="rtl"?"right":"left";this.pages.on("change:current_page",this.pageChangeHandler,this);this.model.on("change:toc_visible",this.windowSizeChangeHandler,this);this.model.on("repagination_event",
this.windowSizeChangeHandler,this);this.model.on("change:current_theme",this.injectTheme,this);this.model.on("change:two_up",this.setUpMode,this);this.model.on("change:two_up",this.adjustIframeColumns,this);this.model.on("change:current_margin",this.marginCallback,this);this.model.on("change:hash_fragment",this.goToHashFragment,this)},render:function(a){var b=this,c=this.model.getCurrentSection().toJSON();this.setUpMode();this.$("#container").html(this.page_template(c));this.$("#readium-flowing-content").on("load",
function(c){b.adjustIframeColumns();b.iframeLoadCallback(c);b.setFontSize();b.injectTheme();b.setNumPages();a?b.pages.goToLastPage():b.pages.goToPage(1)});return[this.model.get("spine_position")]},findVisiblePageElements:function(){var a=$(this.getBody()).find("[id]"),b=$("#readium-flowing-content").contents()[0].documentElement,c=0+$(b).width(),b=0+$(b).height();return this.filterElementsByPosition(a,0,b,0,c)},filterElementsByPosition:function(a,b,c,e,f){return a.filter(function(){var a=$(this).offset().top,
d=$(this).offset().left,g=d+$(this).width(),h=a+$(this).height(),a=a>=b&&h<=c;return d>=e&&g<=f&&a})},indicateMoIsPlaying:function(){(new Readium.Models.MediaOverlayViewHelper({epubController:this.model})).renderReflowableMoPlaying(this.model.get("current_theme"),this.mediaOverlayController.get("active_mo"),this)},highlightText:function(){(new Readium.Models.MediaOverlayViewHelper({epubController:this.model})).renderReflowableMoFragHighlight(this.model.get("current_theme"),this,this.mediaOverlayController.get("mo_text_id"))},
destruct:function(){this.pages.off("change:current_page",this.pageChangeHandler);this.model.off("change:toc_visible",this.windowSizeChangeHandler);this.model.off("repagination_event",this.windowSizeChangeHandler);this.model.off("change:current_theme",this.windowSizeChangeHandler);this.model.off("change:two_up",this.setUpMode);this.model.off("change:two_up",this.adjustIframeColumns);this.model.off("change:current_margin",this.marginCallback);Readium.Views.PaginationViewBase.prototype.destruct.call(this)},
goToPage:function(a){if(!(this.model.get("current_page")!=void 0&&this.model.get("current_page").indexOf(a)!=-1)){var b=this.calcPageOffset(a).toString()+"px";$(this.getBody()).css(this.offset_dir,"-"+b);this.showContent();(this.model.get("two_up")==!1||this.model.get("two_up")&&a%2===1)&&this.mediaOverlayController.reflowPageChanged()}},goToHashFragment:function(){var a=this.model.get("hash_fragment");if(a&&(a=$("#"+a,this.getBody())[0])){for(;a.children.length>0;)a=a.children[0];a=this.getElemPageNumber(a);
a>0&&this.pages.goToPage(a)}},setFontSize:function(){var a=this.model.get("font_size")/10;$(this.getBody()).css("font-size",a+"em");this.setNumPages()},stashModernizrPrefixedProps:function(){var a=function(a){return a.replace(/([A-Z])/g,function(a,b){return"-"+b.toLowerCase()}).replace(/^ms-/,"-ms-")};this.columAxis=Modernizr.prefixed("columnAxis")||"columnAxis";this.columGap=Modernizr.prefixed("columnGap")||"columnGap";this.columWidth=Modernizr.prefixed("columnWidth")||"columnWidth";this.cssColumAxis=
a(this.columAxis);this.cssColumGap=a(this.columGap);this.cssColumWidth=a(this.columWidth)},getBodyColumnCss:function(){var a={};a[this.cssColumAxis]="horizontal";a[this.cssColumGap]=this.gap_width.toString()+"px";a[this.cssColumWidth]=this.page_width.toString()+"px";a.padding="0px";a.margin="0px";a.position="absolute";a.width=this.page_width.toString()+"px";a.height=this.frame_height.toString()+"px";return a},adjustIframeColumns:function(){var a=this.$("#readium-flowing-content");this.setFrameSize();
this.frame_width=parseInt(a.width(),10);this.frame_height=parseInt(a.height(),10);this.gap_width=Math.floor(this.frame_width/7);this.page_width=this.model.get("two_up")?Math.floor((this.frame_width-this.gap_width)/2):this.frame_width;$(this.getBody()).css(this.getBodyColumnCss());this.setNumPages();this.goToPage(this.pages.get("current_page")[0]||1)},getBody:function(){return this.$("#readium-flowing-content").contents()[0].documentElement},hideContent:function(){$("#flowing-wrapper").css("opacity",
"0")},showContent:function(){$("#flowing-wrapper").css("opacity","1")},calcPageOffset:function(a){return(a-1)*(this.page_width+this.gap_width)},setFrameSize:function(){var a=this.getFrameWidth().toString()+"px",b=this.getFrameHeight().toString()+"px";this.$("#readium-flowing-content").attr("width",a);this.$("#readium-flowing-content").attr("height",b);this.$("#readium-flowing-content").css("width",a);this.$("#readium-flowing-content").css("height",b)},getFrameWidth:function(){var a,b=this.model.get("current_margin");
b===1?this.model.get("two_up")?a=0.95:a=0.9:b===2?this.model.get("two_up")?a=0.89:a=0.8:b===3?this.model.get("two_up")?a=0.83:a=0.7:b===4?this.model.get("two_up")?a=0.77:a=0.6:this.model.get("two_up")?a=0.7:a=0.5;return Math.floor($("#flowing-wrapper").width()*a)},getFrameHeight:function(){return $("#flowing-wrapper").height()},calcNumPages:function(){var a,b,c;a=this.getBody();b=a.style[this.offset_dir];a.style[this.offset_dir]="0px";c=this.getBody().scrollWidth;a.style[this.offset_dir]=b;a=Math.floor((c+
this.gap_width)/(this.gap_width+this.page_width));a%2===0&&this.model.get("two_up");return a},getElemPageNumber:function(a){var b,a=a.getClientRects();if(!a||a.length<1)return-1;b=a[0][this.offset_dir];b+=Math.abs(a[0].left-a[0].right);this.offset_dir==="right"&&(b=this.page_width-b);b-=parseInt(this.getBody().style[this.offset_dir],10);return Math.ceil(b/(this.page_width+this.gap_width))},getElemPageNumberById:function(a){var b=$("#readium-flowing-content").contents()[0].documentElement,a=$(b).find("#"+
a);return a.length==0?-1:this.getElemPageNumber(a[0])},pageChangeHandler:function(){var a=this;this.hideContent();setTimeout(function(){a.goToPage(a.pages.get("current_page")[0])},150)},windowSizeChangeHandler:function(){this.adjustIframeColumns()},marginCallback:function(){this.adjustIframeColumns()},themes:{"default-theme":{"background-color":"white",color:"black","mo-color":"#777"},"vancouver-theme":{"background-color":"#DDD",color:"#576b96","mo-color":"#777"},"ballard-theme":{"background-color":"#576b96",
color:"#DDD","mo-color":"#888"},"parchment-theme":{"background-color":"#f7f1cf",color:"#774c27","mo-color":"#eebb22"},"night-theme":{"background-color":"#141414",color:"white","mo-color":"#666"}},injectTheme:function(){var a=this.model.get("current_theme");a==="default"&&(a="default-theme");$(this.getBody()).css({color:this.themes[a].color,"background-color":this.themes[a]["background-color"]});$("#flowing-wrapper").css("visibility","hidden");this.activateEPubStyle(this.getBody());setTimeout(function(){$("#flowing-wrapper").css("visibility",
"visible")},100)},setNumPages:function(){this.pages.set("num_pages",this.calcNumPages())}});
