// save us one ajax call that we will always have to make
// this can also be grabbed by navigating to /epub_content/metadata.json
window.ReadiumLibraryData = [

	{
		current_margin: 1,
		current_theme: "default-theme",
		epub_version: "3.0",
		font_size: 10,
		two_up: true,
		active_class: "",
		apple_fixed: false,
		author: "Matt Garrish",
		cover_href: "/epub_content/accessible_epub_3/EPUB/covers/9781449328030_lrg.jpg",
		created_at: "2012-12-14T00:15:13.446Z",
		description: "",
		epub_version: "3.0",
		file_path: "epub_content/accessible_epub_3/EPUB/package.opf",
		fixed_layout: false,
		id: "urn:isbn:9781449328030",
		key: "accessible_epub_3",
		language: "en",
		layout: "",
		modified_date: "2012-10-24T15:30:00Z",
		ncx: "",
		open_to_spread: false,
		orientation: "",
		package_doc_path: "/epub_content/accessible_epub_3/EPUB/package.opf",
		page_prog_dir: "",
		paginate_backwards: false,
		pubdate: "2012-02-20",
		publisher: "O’Reilly Media, Inc.",
		rights: "",
		root_url: "epub_content/accessible_epub_3/EPUB/package.opf",
		spread: "",
		src_url: "Local Directory: accessible_epub_3-20121024/",
		title: "Accessible EPUB 3",
		updated_at: "2012-12-14T00:24:50.360Z"

	},
	{
		active_class: "",
		apple_fixed: false,
		author: "Jesse Dylan",
		cover_href: "/epub_content/shared_culture/EPUB/images/326261902_3fa36f548d.jpg",
		created_at: "2012-12-14T00:15:13.446Z",
		description: "Multiple video tests (see Navigation Document (toc) for details)",
		epub_version: "3.0",
		file_path: "epub_content/shared_culture/EPUB/package.opf",
		fixed_layout: false,
		id: "code.google.com.epub-samples.cc-shared-culture",
		key: "shared_culture",
		language: "en-US",
		layout: "",
		modified_date: "2012-01-20T12:47:00Z",
		ncx: "",
		open_to_spread: false,
		orientation: "",
		package_doc_path: "/epub_content/shared_culture/EPUB/package.opf",
		page_prog_dir: "",
		paginate_backwards: false,
		pubdate: "",
		publisher: "Creative Commons",
		rights: "",
		root_url: "epub_content/shared_culture/EPUB/package.opf",
		spread: "",
		src_url: "Local Directory: cc-shared-culture-20120130/",
		title: "Creative Commons - A Shared Culture",
		updated_at: "2012-12-14T00:25:08.410Z"
	},
	{
		active_class: "",
		apple_fixed: false,
		author: "Charles Madison CurryErle Elsworth Clippinger",
		cover_href: "epub_content/children_lit/EPUB/images/cover.png",
		created_at: "2012-12-14T00:15:13.446Z",
		description: "",
		epub_version: "3.0",
		file_path: "epub_content/children_lit/EPUB/package.opf",
		fixed_layout: false,
		id: "http://www.gutenberg.org/ebooks/25545",
		key: "children_lit",
		language: "en",
		layout: "",
		modified_date: "2010-02-17T04:39:13Z",
		ncx: "",
		open_to_spread: false,
		orientation: "",
		package_doc_path: "/epub_content/children_lit/EPUB/package.opf",
		page_prog_dir: "",
		paginate_backwards: false,
		pubdate: "2008-05-20",
		publisher: "",
		rights: "",
		root_url: "epub_content/children_lit/EPUB/package.opf",
		spread: "",
		src_url: "Local Directory: childrens-literature-20120722/",
		title: "Children's LiteratureA Textbook of Sources for Teachers and Teacher-Training Classes",
		updated_at: "2012-12-14T00:26:20.222Z"
	},

	{
		active_class: "",
		apple_fixed: false,
		author: "Thomas Crane",
		cover_href: "/images/library/missing-cover-image.png",
		created_at: "2012-12-14T00:26:27.743Z",
		description: "",
		epub_version: "3.0",
		file_path: "epub_content/abroad/EPUB/content.opf",
		fixed_layout: false,
		id: "urn:uuid:12C1DF3E-DF35-4FCF-918B-643FF15A7870",
		key: "abroad",
		language: "en",
		layout: "",
		modified_date: "2012-04-09T12:00:00Z",
		ncx: "ncx",
		open_to_spread: false,
		orientation: "",
		package_doc_path: "/epub_content/abroad/EPUB/content.opf",
		page_prog_dir: "",
		paginate_backwards: false,
		pubdate: "1882",
		publisher: "London ; Belfast ; New York : Marcus Ward & Co.",
		rights: "This work (Abroad EPUB 3), identified by Liza Daly, is free of known copyright restrictions.",
		root_url: "epub_content/abroad/EPUB/content.opf",
		spread: "",
		src_url: "Local Directory: childrens-media-query-20120412/",
		title: "Abroad",
		updated_at: "2012-12-14T00:26:37.013Z"

	},

	{
		active_class: "",
		apple_fixed: false,
		author: "Jesse Dylan",
		cover_href: "epub_content/thomas_cole/EPUB/images/portrait.jpg",
		created_at: "2012-12-14T00:26:39.672Z",
		description: "",
		epub_version: "3.0",
		file_path: "epub_content/thomas_cole/EPUB/cole.opf",
		fixed_layout: false,
		id: "code.google.com.epub-samples.cole-voyage-of-life",
		key: "thomas_cole",
		language: "en-US",
		layout: "",
		modified_date: "2012-03-20T11:37:00Z",
		ncx: "",
		open_to_spread: false,
		orientation: "",
		package_doc_path: "/epub_content/thomas_cole/EPUB/cole.opf",
		page_prog_dir: "",
		paginate_backwards: false,
		pubdate: "",
		publisher: "",
		rights: "This work is licensed under a Creative Commons Attribution-ShareAlike 3.0 Unported License.",
		root_url: "epub_content/thomas_cole/EPUB/cole.opf",
		spread: "",
		src_url: "Local Directory: cole-voyage-of-life-20120320/",
		title: "Thomas Cole - The Voyage of Life",
		updated_at: "2012-12-14T00:26:50.641Z"
	},

	{
		active_class: "",
		apple_fixed: false,
		author: "Jesse Dylan",
		cover_href: "epub_content/thomas_cole_tol/EPUB/images/portrait.jpg",
		created_at: "2012-12-14T00:26:52.778Z",
		description: "Mixed reflowable/fixed with an expermental textual overlay (click or tap on paintings to activate)",
		epub_version: "3.0",
		file_path: "epub_content/thomas_cole_tol/EPUB/cole.opf",
		fixed_layout: true,
		id: "code.google.com.epub-samples.cole-voyage-of-life-tol",
		key: "thomas_cole_tol",
		language: "en-US",
		layout: "pre-paginated",
		modified_date: "2012-04-02T12:47:00Z",
		ncx: "",
		open_to_spread: false,
		orientation: "landscape",
		package_doc_path: "/epub_content/thomas_cole_tol/EPUB/cole.opf",
		page_prog_dir: "",
		paginate_backwards: false,
		pubdate: "",
		publisher: "",
		rights: "This work is licensed under a Creative Commons Attribution-ShareAlike 3.0 Unported License.",
		root_url: "epub_content/thomas_cole_tol/EPUB/cole.opf",
		spread: "none",
		src_url: "Local Directory: cole-voyage-of-life-tol-20120405 (1)/",
		title: "Thomas Cole - The Voyage of Life",
		updated_at: "2012-12-14T00:27:02.817Z"
	},

	{
		active_class: "",
		apple_fixed: false,
		author: "EPUB 3 Working Group",
		cover_href: "epub_content/epub_spec30_1/EPUB/img/epub_logo_color.jpg",
		created_at: "2012-12-14T00:27:04.993Z",
		description: "",
		epub_version: "3.0",
		file_path: "epub_content/epub_spec30_1/EPUB/package.opf",
		fixed_layout: false,
		id: "code.google.com.epub-samples.epub30-spec",
		key: "epub_spec30_1",
		language: "en",
		layout: "",
		modified_date: "2012-02-27T16:38:35Z",
		ncx: "",
		open_to_spread: false,
		orientation: "",
		package_doc_path: "/epub_content/epub_spec30_1/EPUB/package.opf",
		page_prog_dir: "",
		paginate_backwards: false,
		pubdate: "",
		publisher: "",
		rights: "",
		root_url: "epub_content/epub_spec30_1/EPUB/package.opf",
		spread: "",
		src_url: "Local Directory: epub30-spec-20120228/",
		title: "EPUB 3.0 Specification",
		updated_at: "2012-12-14T00:27:15.759Z"
	},

	{
		active_class: "",
		apple_fixed: false,
		author: "Various",
		cover_href: "epub_content/georgia_cfi/EPUB/images/cover.png",
		created_at: "2012-12-14T00:27:18.268Z",
		description: "",
		epub_version: "3.0",
		file_path: "epub_content/georgia_cfi/EPUB/package.opf",
		fixed_layout: false,
		id: "code.google.com.epub-samples.georgia-cfi",
		key: "georgia_cfi",
		language: "en-US",
		layout: "",
		modified_date: "2012-02-07T16:38:35Z",
		ncx: "",
		open_to_spread: false,
		orientation: "",
		package_doc_path: "/epub_content/georgia_cfi/EPUB/package.opf",
		page_prog_dir: "",
		paginate_backwards: false,
		pubdate: "",
		publisher: "",
		rights: "",
		root_url: "epub_content/georgia_cfi/EPUB/package.opf",
		spread: "",
		src_url: "Local Directory: georgia-cfi-20120521 (2)/",
		title: "Georgia",
		updated_at: "2012-12-14T00:27:37.702Z"
	},

	{
		active_class: "",
		apple_fixed: false,
		author: "Various",
		cover_href: "epub_content/georgia/EPUB/images/cover.png",
		created_at: "2012-12-14T00:27:53.728Z",
		description: "",
		epub_version: "3.0",
		file_path: "epub_content/georgia/EPUB/package.opf",
		fixed_layout: false,
		id: "code.google.com.epub-samples.georgia-pls-ssml",
		key: "georgia",
		language: "en-US",
		layout: "",
		modified_date: "2012-02-07T16:38:35Z",
		ncx: "ncx",
		open_to_spread: false,
		orientation: "",
		package_doc_path: "/epub_content/georgia/EPUB/package.opf",
		page_prog_dir: "",
		paginate_backwards: false,
		pubdate: "",
		publisher: "",
		rights: "",
		root_url: "epub_content/georgia/EPUB/package.opf",
		spread: "",
		src_url: "Local Directory: georgia-pls-ssml-20120322 (1)/",
		title: "Georgia",
		updated_at: "2012-12-14T00:28:02.150Z"
	},

	{
		active_class: "",
		apple_fixed: false,
		author: "",
		cover_href: "/images/library/missing-cover-image.png",
		created_at: "2012-12-14T00:28:16.113Z",
		description: "",
		epub_version: "3.0",
		file_path: "epub_content/hefty_water/EPUB/package.opf",
		fixed_layout: false,
		id: "code.google.com.epub-samples.hefty.water",
		key: "hefty_water",
		language: "en",
		layout: "",
		modified_date: "2012-03-29T12:00:00Z",
		ncx: "",
		open_to_spread: false,
		orientation: "",
		package_doc_path: "/epub_content/hefty_water/EPUB/package.opf",
		page_prog_dir: "",
		paginate_backwards: false,
		pubdate: "2012-03-29",
		publisher: "",
		rights: "",
		root_url: "epub_content/hefty_water/EPUB/package.opf",
		spread: "",
		src_url: "Local Directory: hefty-water-20120404/",
		title: "Hefty Water",
		updated_at: "2012-12-14T00:28:27.012Z"
	},

	{
		active_class: "",
		apple_fixed: false,
		author: "",
		cover_href: "/images/library/missing-cover-image.png",
		created_at: "2012-12-14T00:28:31.331Z",
		description: "",
		epub_version: "3.0",
		file_path: "epub_content/kusamakura/OPS/package.opf",
		fixed_layout: false,
		id: "http://www.aozora.gr.jp/cards/000148/card776.html",
		key: "kusamakura",
		language: "ja-jp",
		layout: "",
		modified_date: "2012-04-24T00:00:00Z",
		ncx: "ncxtoc",
		open_to_spread: false,
		orientation: "",
		package_doc_path: "/epub_content/kusamakura/OPS/package.opf",
		page_prog_dir: "rtl",
		paginate_backwards: false,
		pubdate: "",
		publisher: "",
		rights: "",
		root_url: "epub_content/kusamakura/OPS/package.opf",
		spread: "",
		src_url: "Local Directory: kusamakura-japanese-vertical-writing-20121124/",
		title: "草枕",
		updated_at: "2012-12-14T00:28:43.005Z"
	},

	{
		active_class: "",
		apple_fixed: false,
		author: "Herman Melville",
		cover_href: "epub_content/moby_dick/OPS/images/9780316000000.jpg",
		created_at: "2012-12-14T00:28:53.532Z",
		description: "",
		epub_version: "3.0",
		file_path: "epub_content/moby_dick/OPS/package.opf",
		fixed_layout: false,
		id: "code.google.com.epub-samples.moby-dick-basic",
		key: "moby_dick",
		language: "en-US",
		layout: "",
		modified_date: "2012-01-18T12:47:00Z",
		ncx: "",
		open_to_spread: false,
		orientation: "",
		package_doc_path: "/epub_content/moby_dick/OPS/package.opf",
		page_prog_dir: "",
		paginate_backwards: false,
		pubdate: "",
		publisher: "Harper & Brothers, Publishers",
		rights: "This work is shared with the public using the Attribution-ShareAlike 3.0 Unported (CC BY-SA 3.0) license.",
		root_url: "epub_content/moby_dick/OPS/package.opf",
		spread: "",
		src_url: "Local Directory: moby-dick-20120118/",
		title: "Moby-Dick",
		updated_at: "2012-12-14T00:29:31.560Z"
	},

	{
		active_class: "",
		apple_fixed: false,
		author: "Boulet",
		cover_href: "epub_content/page_blanche/EPUB/Image/cover.jpg",
		created_at: "2012-12-14T00:29:34.512Z",
		description: "",
		epub_version: "3.0",
		file_path: "epub_content/page_blanche/EPUB/package.opf",
		fixed_layout: true,
		id: "code.google.com.epub-samples.page-blanche",
		key: "page_blanche",
		language: "fr",
		layout: "pre-paginated",
		modified_date: "2012-08-28T18:00:00Z",
		ncx: "ncx",
		open_to_spread: false,
		orientation: "auto",
		package_doc_path: "/epub_content/page_blanche/EPUB/package.opf",
		page_prog_dir: "",
		paginate_backwards: false,
		pubdate: "2012-01-18",
		publisher: "éditions Delcourt",
		rights: "This work is shared with the public using the Attribution-ShareAlike 3.0 Unported (CC BY-SA 3.0) license.",
		root_url: "epub_content/page_blanche/EPUB/package.opf",
		spread: "auto",
		src_url: "Local Directory: page-blanche-20121022/",
		title: "Page Blanche",
		updated_at: "2012-12-14T00:30:03.741Z"
	},

	{
		active_class: "",
		apple_fixed: false,
		author: "Boulet",
		cover_href: "epub_content/page_blanche_bitmap/EPUB/Image/cover.jpg",
		created_at: "2012-12-14T00:30:05.990Z",
		description: "",
		epub_version: "3.0",
		file_path: "epub_content/page_blanche_bitmap/EPUB/package.opf",
		fixed_layout: true,
		id: "code.google.com.epub-samples.page-blanche_bitmaps-in-spine",
		key: "page_blanche_bitmap",
		language: "fr",
		layout: "pre-paginated",
		modified_date: "2012-08-08T15:00:00Z",
		ncx: "ncx",
		open_to_spread: false,
		orientation: "auto",
		package_doc_path: "/epub_content/page_blanche_bitmap/EPUB/package.opf",
		page_prog_dir: "",
		paginate_backwards: false,
		pubdate: "2012-01-18",
		publisher: "éditions Delcourt",
		rights: "This work is shared with the public using the Attribution-ShareAlike 3.0 Unported (CC BY-SA 3.0) license.",
		root_url: "epub_content/page_blanche_bitmap/EPUB/package.opf",
		spread: "auto",
		src_url: "Local Directory: page-blanche-bitmaps-in-spine-20120809/",
		title: "Page Blanche (bitmaps directly in spine)",
		updated_at: "2012-12-14T00:30:12.867Z"
	},

	{
		active_class: "",
		apple_fixed: false,
		author: "Pr David Khayat",
		cover_href: "epub_content/anti_cancer/EPUB/Image/cover.jpg",
		created_at: "2012-12-14T00:31:12.800Z",
		description: "",
		epub_version: "3.0",
		file_path: "epub_content/anti_cancer/EPUB/package.opf",
		fixed_layout: false,
		id: "code.google.com.epub-samples.regime-anticancer-arabic",
		key: "anti_cancer",
		language: "ar",
		layout: "",
		modified_date: "2012-08-28T18:00:00Z",
		ncx: "ncx",
		open_to_spread: false,
		orientation: "",
		package_doc_path: "/epub_content/anti_cancer/EPUB/package.opf",
		page_prog_dir: "rtl",
		paginate_backwards: false,
		pubdate: "2012",
		publisher: "Hachette Antoine",
		rights: "This work is shared with the public using the Attribution-ShareAlike 3.0 Unported (CC BY-SA 3.0) license.",
		root_url: "epub_content/anti_cancer/EPUB/package.opf",
		spread: "",
		src_url: "Local Directory: regime-anticancer-arabic-20121022/",
		title: "Le Vrai Régime anti-cancer",
		updated_at: "2012-12-14T00:31:25.889Z"
	},

	{
		active_class: "",
		apple_fixed: false,
		author: "佐野眞一",
		cover_href: "epub_content/sash_for_you/OEBPS/images/cover_image.jpg",
		created_at: "2012-12-14T00:31:36.832Z",
		description: "",
		epub_version: "3.0",
		file_path: "epub_content/sash_for_you/OEBPS/sash_for_you.opf",
		fixed_layout: false,
		id: "urn:uuid:E48047B8-3676-4CB7-8C02-966AA64C84FF",
		key: "sash_for_you",
		language: "ja",
		layout: "",
		modified_date: "2012-07-10T09:30:00Z",
		ncx: "",
		open_to_spread: false,
		orientation: "",
		package_doc_path: "/epub_content/sash_for_you/OEBPS/sash_for_you.opf",
		page_prog_dir: "rtl",
		paginate_backwards: false,
		pubdate: "2012-06-26T00:00:00Z",
		publisher: "株式会社ボイジャー",
		rights: "",
		root_url: "epub_content/sash_for_you/OEBPS/sash_for_you.opf",
		spread: "",
		src_url: "Local Directory: sash-for-you-20120827/",
		title: "君に渡す襷として",
		updated_at: "2012-12-14T00:31:48.612Z"
	},

	{
		active_class: "",
		apple_fixed: false,
		author: "Jean-Bernard Pouy",
		cover_href: "epub_content/sous_le_vent/EPUB/Image/cover.jpg",
		created_at: "2012-12-14T00:32:39.572Z",
		description: "",
		epub_version: "3.0",
		file_path: "epub_content/sous_le_vent/EPUB/package.opf",
		fixed_layout: true,
		id: "code.gogle.com.epub-sample.sous-le-vent_svg-in-spine",
		key: "sous_le_vent",
		language: "fr",
		layout: "pre-paginated",
		modified_date: "2012-08-28T18:00:00Z",
		ncx: "ncx",
		open_to_spread: false,
		orientation: "portrait",
		package_doc_path: "/epub_content/sous_le_vent/EPUB/package.opf",
		page_prog_dir: "",
		paginate_backwards: false,
		pubdate: "2012-02-01",
		publisher: "éditions Jean-Claude Lattès",
		rights: "This work is shared with the public using the Attribution-ShareAlike 3.0 Unported (CC BY-SA 3.0) license.",
		root_url: "epub_content/sous_le_vent/EPUB/package.opf",
		spread: "none",
		src_url: "Local Directory: sous-le-vent_svg-in-spine-20121022/",
		title: "Sous le vent (SVG directly in spine)",
		updated_at: "2012-12-14T00:32:49.394Z"
	},

	{
		active_class: "",
		apple_fixed: false,
		author: "Jean-Bernard Pouy",
		cover_href: "epub_content/sous_le_vent_2/EPUB/Image/9782709641609_Couv.jpg",
		created_at: "2012-12-14T00:32:52.439Z",
		description: "",
		epub_version: "3.0",
		file_path: "epub_content/sous_le_vent_2/EPUB/package.opf",
		fixed_layout: true,
		id: "code.gogle.com.epub-sample.sous-le-vent",
		key: "sous_le_vent_2",
		language: "fr",
		layout: "pre-paginated",
		modified_date: "2012-08-28T18:00:00Z",
		ncx: "ncx",
		open_to_spread: false,
		orientation: "portrait",
		package_doc_path: "/epub_content/sous_le_vent_2/EPUB/package.opf",
		page_prog_dir: "",
		paginate_backwards: false,
		pubdate: "2012-02-01",
		publisher: "éditions Jean-Claude Lattès",
		rights: "This work is shared with the public using the Attribution-ShareAlike 3.0 Unported (CC BY-SA 3.0) license.",
		root_url: "epub_content/sous_le_vent_2/EPUB/package.opf",
		spread: "auto",
		src_url: "Local Directory: sous-le-vent-20121022/",
		title: "Sous le vent",
		updated_at: "2012-12-14T00:33:03.634Z"
	},

	{
		active_class: "",
		apple_fixed: false,
		author: "ePub Sample project",
		cover_href: "epub_content/svg_in_spine/OPS/Images/cover.svg",
		created_at: "2012-12-14T00:33:05.922Z",
		description: "SVG files are directly called from spine. A page needs to be skipped to display when it is in landscape.",
		epub_version: "3.0",
		file_path: "epub_content/svg_in_spine/OPS/content.opf",
		fixed_layout: true,
		id: "code.google.com.epub-samples.svg-in-spine",
		key: "svg_in_spine",
		language: "en-US",
		layout: "pre-paginated",
		modified_date: "2012-04-12T12:00:00Z",
		ncx: "",
		open_to_spread: false,
		orientation: "",
		package_doc_path: "/epub_content/svg_in_spine/OPS/content.opf",
		page_prog_dir: "",
		paginate_backwards: false,
		pubdate: "",
		publisher: "ePub Sample",
		rights: "This work is licensed under a Creative Commons Attribution (CC BY SA) license.",
		root_url: "epub_content/svg_in_spine/OPS/content.opf",
		spread: "",
		src_url: "Local Directory: svg-in-spine-20120417/",
		title: "SVG in Spine",
		updated_at: "2012-12-14T00:33:19.469Z"
	},

	{
		active_class: "",
		apple_fixed: false,
		author: "",
		cover_href: "epub_content/trees/EPUB/cover.jpg",
		created_at: "2012-12-14T00:34:37.612Z",
		description: "Test of canvas element and CSS3 multi-column layout",
		epub_version: "3.0",
		file_path: "epub_content/trees/EPUB/package.opf",
		fixed_layout: false,
		id: "code.google.com.epub-samples.trees",
		key: "trees",
		language: "en",
		layout: "",
		modified_date: "2012-04-05T12:47:00Z",
		ncx: "",
		open_to_spread: false,
		orientation: "",
		package_doc_path: "/epub_content/trees/EPUB/package.opf",
		page_prog_dir: "",
		paginate_backwards: false,
		pubdate: "",
		publisher: "",
		rights: "",
		root_url: "epub_content/trees/EPUB/package.opf",
		spread: "",
		src_url: "Local Directory: trees-20120417 (1)/",
		title: "Trees",
		updated_at: "2012-12-14T00:34:46.625Z"
	},

	{
		active_class: "",
		apple_fixed: false,
		author: "T.S. Eliot",
		cover_href: "epub_content/wasteland/EPUB/wasteland-cover.jpg",
		created_at: "2012-12-14T00:34:49.120Z",
		description: "",
		epub_version: "3.0",
		file_path: "epub_content/wasteland/EPUB/wasteland.opf",
		fixed_layout: false,
		id: "code.google.com.epub-samples.wasteland-basic",
		key: "wasteland",
		language: "en-US",
		layout: "",
		modified_date: "2012-01-18T12:47:00Z",
		ncx: "ncx",
		open_to_spread: false,
		orientation: "",
		package_doc_path: "/epub_content/wasteland/EPUB/wasteland.opf",
		page_prog_dir: "",
		paginate_backwards: false,
		pubdate: "2011-09-01",
		publisher: "",
		rights: "This work is shared with the public using the Attribution-ShareAlike 3.0 Unported (CC BY-SA 3.0) license.",
		root_url: "epub_content/wasteland/EPUB/wasteland.opf",
		spread: "",
		src_url: "Local Directory: wasteland-20120118 (1)/",
		title: "The Waste Land",
		updated_at: "2012-12-14T00:34:59.873Z"
	},

	{
		active_class: "",
		apple_fixed: false,
		author: "T.S. Eliot",
		cover_href: "epub_content/wasteland_otf/EPUB/wasteland-cover.jpg",
		created_at: "2012-12-14T00:35:10.272Z",
		description: "Using OTF fonts, fallback to sans-serif system font",
		epub_version: "3.0",
		file_path: "epub_content/wasteland_otf/EPUB/wasteland.opf",
		fixed_layout: false,
		id: "code.google.com.epub-samples.wasteland-otf",
		key: "wasteland_otf",
		language: "en-US",
		layout: "",
		modified_date: "2012-01-18T12:47:00Z",
		ncx: "ncx",
		open_to_spread: false,
		orientation: "",
		package_doc_path: "/epub_content/wasteland_otf/EPUB/wasteland.opf",
		page_prog_dir: "",
		paginate_backwards: false,
		pubdate: "2011-09-01",
		publisher: "",
		rights: "This work is shared with the public using the Attribution-ShareAlike 3.0 Unported (CC BY-SA 3.0) license.",
		root_url: "epub_content/wasteland_otf/EPUB/wasteland.opf",
		spread: "",
		src_url: "Local Directory: wasteland-otf-20120118/",
		title: "The Waste Land",
		updated_at: "2012-12-14T00:35:23.875Z"
	},

	{
		active_class: "",
		apple_fixed: false,
		author: "T.S. Eliot",
		cover_href: "epub_content/wasteland_otf_obfs/EPUB/wasteland-cover.jpg",
		created_at: "2012-12-14T00:35:26.256Z",
		description: "OTF font obfuscated using algorithm defined in OCF 3.0, fallback to sans-serif system font",
		epub_version: "3.0",
		file_path: "epub_content/wasteland_otf_obfs/EPUB/wasteland.opf",
		fixed_layout: false,
		id: "code.google.com.epub-samples.wasteland-otf-obfuscated",
		key: "wasteland_otf_obfs",
		language: "en-US",
		layout: "",
		modified_date: "2012-01-18T12:47:00Z",
		ncx: "ncx",
		open_to_spread: false,
		orientation: "",
		package_doc_path: "/epub_content/wasteland_otf_obfs/EPUB/wasteland.opf",
		page_prog_dir: "",
		paginate_backwards: false,
		pubdate: "2011-09-01",
		publisher: "",
		rights: "This work is shared with the public using the Attribution-ShareAlike 3.0 Unported (CC BY-SA 3.0) license.",
		root_url: "epub_content/wasteland_otf_obfs/EPUB/wasteland.opf",
		spread: "",
		src_url: "Local Directory: wasteland-otf-obf-20120118 (1)/",
		title: "The Waste Land",
		updated_at: "2012-12-14T00:35:43.726Z"
	},

	{
		active_class: "",
		apple_fixed: false,
		author: "T.S. Eliot",
		cover_href: "epub_content/wasteland_woff/EPUB/wasteland-cover.jpg",
		created_at: "2012-12-14T00:35:46.783Z",
		description: "Using WOFF fonts, fallback to sans-serif system font",
		epub_version: "3.0",
		file_path: "epub_content/wasteland_woff/EPUB/wasteland.opf",
		fixed_layout: false,
		id: "code.google.com.epub-samples.wasteland-woff",
		key: "wasteland_woff",
		language: "en-US",
		layout: "",
		modified_date: "2012-01-18T12:47:00Z",
		ncx: "ncx",
		open_to_spread: false,
		orientation: "",
		package_doc_path: "/epub_content/wasteland_woff/EPUB/wasteland.opf",
		page_prog_dir: "",
		paginate_backwards: false,
		pubdate: "2011-09-01",
		publisher: "",
		rights: "This work is shared with the public using the Attribution-ShareAlike 3.0 Unported (CC BY-SA 3.0) license.",
		root_url: "epub_content/wasteland_woff/EPUB/wasteland.opf",
		spread: "",
		src_url: "Local Directory: wasteland-woff-20120118/",
		title: "The Waste Land",
		updated_at: "2012-12-14T00:35:59.408Z"	
	},

	{
		active_class: "",
		apple_fixed: false,
		author: "T.S. Eliot",
		cover_href: "epub_content/wasteland_woff_obfs/EPUB/wasteland-cover.jpg",
		created_at: "2012-12-14T00:36:03.859Z",
		description: "WOFF font obfuscated using algorithm defined in OCF 3.0, fallback to sans-serif system font",
		epub_version: "3.0",
		file_path: "epub_content/wasteland_woff_obfs/EPUB/wasteland.opf",
		fixed_layout: false,
		id: "code.google.com.epub-samples.wasteland-woff-obfuscated",
		key: "wasteland_woff_obfs",
		language: "en-US",
		layout: "",
		modified_date: "2012-01-18T12:47:00Z",
		ncx: "ncx",
		open_to_spread: false,
		orientation: "",
		package_doc_path: "/epub_content/wasteland_woff_obfs/EPUB/wasteland.opf",
		page_prog_dir: "",
		paginate_backwards: false,
		pubdate: "2011-09-01",
		publisher: "",
		rights: "This work is shared with the public using the Attribution-ShareAlike 3.0 Unported (CC BY-SA 3.0) license.",
		root_url: "epub_content/wasteland_woff_obfs/EPUB/wasteland.opf",
		spread: "",
		src_url: "Local Directory: wasteland-woff-obf-20120118 (1)/",
		title: "The Waste Land",
		updated_at: "2012-12-14T00:36:13.585Z"
	},

	{
		active_class: "",
		apple_fixed: false,
		author: "E.L. Starr",
		cover_href: "epub_content/widgets/EPUB/images/cover.jpg",
		created_at: "2012-12-14T00:36:15.860Z",
		description: "",
		epub_version: "3.0",
		file_path: "/epub_content/widgets/EPUB/package.opf",
		fixed_layout: false,
		id: "code.google.com.epub-samples.widget-figure-gallery",
		key: "widgets",
		language: "en-US",
		layout: "",
		modified_date: "2012-04-05T21:03:00Z",
		ncx: "ncx",
		open_to_spread: false,
		orientation: "",
		package_doc_path: "/epub_content/widgets/EPUB/package.opf",
		page_prog_dir: "",
		paginate_backwards: false,
		pubdate: "2012-01-17",
		publisher: "",
		rights: "This work is shared with the public using the Attribution-ShareAlike 3.0 Unported (CC BY-SA 3.0) license.",
		root_url: "/epub_content/widgets/EPUB/package.opf",
		spread: "",
		src_url: "Local Directory: widget-figure-gallery-20121022/",
		title: "EPUB Widgets: Figure Gallery",
		updated_at: "2012-12-14T00:36:25.987Z"
	},

	{
		active_class: "",
		apple_fixed: false,
		author: "E.L. Starr",
		cover_href: "epub_content/widgets_quiz/EPUB/images/cover.jpg",
		created_at: "2012-12-14T00:36:28.253Z",
		description: "",
		epub_version: "3.0",
		file_path: "epub_content/widgets_quiz/EPUB/package.opf",
		fixed_layout: false,
		id: "code.google.com.epub-samples.widget-quiz",
		key: "widgets_quiz",
		language: "en-US",
		layout: "",
		modified_date: "2012-04-05T21:03:00Z",
		ncx: "ncx",
		open_to_spread: false,
		orientation: "",
		package_doc_path: "/epub_content/widgets_quiz/EPUB/package.opf",
		page_prog_dir: "",
		paginate_backwards: false,
		pubdate: "2012-01-17",
		publisher: "",
		rights: "This work is shared with the public using the Attribution-ShareAlike 3.0 Unported (CC BY-SA 3.0) license.",
		root_url: "epub_content/widgets_quiz/EPUB/package.opf",
		spread: "",
		src_url: "Local Directory: widget-quiz-20121022/",
		title: "EPUB Widgets: Quiz",
		updated_at: "2012-12-14T00:36:36.163Z"
	},

	{
		active_class: "-epub-media-overlay-active",
		apple_fixed: false,
		author: "Herman Melville",
		cover_href: "epub_content/moby_dick_mo/OPS/images/9780316000000.jpg",
		created_at: "2012-12-14T00:32:39.572Z",
		description: "",
		epub_version: "3.0",
		file_path: "epub_content/moby_dick_mo/OPS/package.opf",
		fixed_layout: false,
		id: "urn:isbn:9780316000000",
		key: "moby_dick_mo",
		language: "en-US",
		layout: "",
		modified_date: "2012-01-13T01:13:00Z",
		ncx: "",
		open_to_spread: false,
		orientation: "",
		package_doc_path: "/epub_content/moby_dick_mo/OPS/package.opf",
		page_prog_dir: "",
		paginate_backwards: false,
		pubdate: "",
		publisher: "Harper & Brothers, Publishers",
		rights: "",
		root_url: "epub_content/moby_dick_mo/OPS/package.opf",
		spread: "",
		src_url: "Local Directory: moby-dick-mo-20120214 (2)/",
		title: "Moby-Dick",
		updated_at: "2012-12-14T00:43:18.958Z"
	},

	{
		active_class: "",
		apple_fixed: false,
		author: "",
		cover_href: "epub_content/mahabharata/EPUB/img/mahabharata.jpg",
		created_at: "2012-12-14T00:43:22.302Z",
		description: "",
		epub_version: "3.0",
		file_path: "epub_content/mahabharata/EPUB/mahabharata.opf",
		fixed_layout: false,
		id: "code.google.com.epub-samples.mahabarata",
		key: "mahabharata",
		language: "sa",
		layout: "",
		modified_date: "2012-03-01T12:47:00Z",
		ncx: "",
		open_to_spread: false,
		orientation: "",
		package_doc_path: "/epub_content/mahabharata/EPUB/mahabharata.opf",
		page_prog_dir: "",
		paginate_backwards: false,
		pubdate: "",
		publisher: "",
		rights: "This work is shared with the public using the Attribution-ShareAlike 3.0 Unported (CC BY-SA 3.0) license.",
		root_url: "epub_content/mahabharata/EPUB/mahabharata.opf",
		spread: "",
		src_url: "Local Directory: mahabharata-20120305/",
		title: "महाभारत",
		updated_at: "2012-12-14T00:47:23.749Z"
	},

	{
		active_class: "",
		apple_fixed: false,
		author: "Robert A. Beezer",
		cover_href: "/images/library/missing-cover-image.png",
		created_at: "2012-12-14T00:47:28.528Z",
		description: "",
		epub_version: "3.0",
		file_path: "epub_content/linear_algebra/EPUB/package.opf",
		fixed_layout: false,
		id: "code.google.com.epub-samples.linear-algebra",
		key: "linear_algebra",
		language: "en",
		layout: "",
		modified_date: "2012-03-05T12:47:00Z",
		ncx: "",
		open_to_spread: false,
		orientation: "",
		package_doc_path: "/epub_content/linear_algebra/EPUB/package.opf",
		page_prog_dir: "",
		paginate_backwards: false,
		pubdate: "",
		publisher: "",
		rights: "This work is shared with the public using the GNU Free Documentation License, Version 1.2.",
		root_url: "epub_content/linear_algebra/EPUB/package.opf",
		spread: "",
		src_url: "Local Directory: linear-algebra-20120306 (1)/",
		title: "A First Course in Linear Algebra",
		updated_at: "2012-12-14T00:48:22.950Z"
	},

	{
		active_class: "",
		apple_fixed: false,
		author: "W3C® (MIT, ERCIM, Keio)",
		cover_href: "/images/library/missing-cover-image.png",
		created_at: "2012-12-14T00:48:28.618Z",
		description: "This document describes requirements for general Japanese layout realized with technologies like CSS, SVG and XSL-FO. The document is mainly based on a standard for Japanese layout, JIS X 4051, however, it also addresses areas which are not covered by JIS X 4051. This second version of the document contains a significant amount of additional information related to hanmen design, such as handling headings, placement of illustrations and tables, handling of notes and reference marks, etc.",
		epub_version: "3.0",
		file_path: "epub_content/req_japanese_layout/OEBPS/jlreq.opf",
		fixed_layout: false,
		id: "http://www.w3.org/TR/2012/NOTE-jlreq-20120403/",
		key: "req_japanese_layout",
		language: "en",
		layout: "",
		modified_date: "2012-04-03T00:00:00Z",
		ncx: "ncx",
		open_to_spread: false,
		orientation: "",
		package_doc_path: "/epub_content/req_japanese_layout/OEBPS/jlreq.opf",
		page_prog_dir: "",
		paginate_backwards: false,
		pubdate: "2012-04-03",
		publisher: "W3C® (MIT, ERCIM, Keio)",
		rights: "Copyright © 2012 W3C® (MIT, ERCIM, Keio), All Rights Reserved. W3C liability, trademark and document use rules apply.",
		root_url: "epub_content/req_japanese_layout/OEBPS/jlreq.opf",
		spread: "",
		src_url: "Local Directory: jlreq_20120525/",
		title: "Requirements for Japanese Text Layout",
		updated_at: "2012-12-14T00:49:22.024Z"
	},

	{
		active_class: "",
		apple_fixed: false,
		author: "W3C® (MIT, ERCIM, Keio)",
		cover_href: "/images/library/missing-cover-image.png",
		created_at: "2012-12-14T00:49:26.426Z",
		description: "この文書は，CSS，SVGおよびXSL-FOなどの技術で実現が求められる一般的な日本語組版の要件を記述したものです．この文書は，主としてJIS X 4051（日本語組版規則）に基づいていますが，一部，JIS X 4051に記載されていない事項にも言及しています．この第2版は，見出しの扱い，図版や表の配置，注や合印等の版面デザインに関する多くの情報が増補されています. ",
		epub_version: "3.0",
		file_path: "epub_content/req_japanese_layout_2/OEBPS/jlreq_ja.opf",
		fixed_layout: false,
		id: "http://www.w3.org/TR/2012/NOTE-jlreq-20120403/ja/",
		key: "req_japanese_layout_2",
		language: "ja",
		layout: "",
		modified_date: "2012-04-03T00:00:00Z",
		ncx: "ncx",
		open_to_spread: false,
		orientation: "",
		package_doc_path: "/epub_content/req_japanese_layout_2/OEBPS/jlreq_ja.opf",
		page_prog_dir: "",
		paginate_backwards: false,
		pubdate: "2012-04-03",
		publisher: "W3C® (MIT, ERCIM, Keio)",
		rights: "Copyright © 2012 W3C® (MIT, ERCIM, Keio), All Rights Reserved. W3C liability, trademark and document use rules apply.",
		root_url: "epub_content/req_japanese_layout_2/OEBPS/jlreq_ja.opf",
		spread: "",
		src_url: "Local Directory: jlreq_20120525_ja (1)/",
		title: "日本語組版処理の要件（日本語版）",
		updated_at: "2012-12-14T00:50:26.124Z"
	},

	{
		active_class: "",
		apple_fixed: false,
		author: "אורי עידן",
		cover_href: "epub_content/israeli_sailing/OEPBS/israelsailing.jpg",
		created_at: "2012-12-14T00:50:29.804Z",
		description: "כשנתיים לאחר תום הסיפור רחשי הלב האחרונים אבישי גר ביאכטה שלו במרינה הרצליה. לפתע הוא מקבל ביקור בלתי צפוי. ביקור זה מוביל להרפתקאות מעניינות לאורך חופי הארץ.↵כמו בשאר הספרים על אבישי, אין צורך לקרוא את הספרים האחרים על מנת להבין סיפור זה.",
		epub_version: "3.0",
		file_path: "epub_content/israeli_sailing/OEPBS/content.opf",
		fixed_layout: false,
		id: "http://www.thestories.org/book/israelsailing",
		key: "israeli_sailing",
		language: "he",
		layout: "",
		modified_date: "2012-08-19T18:03:16Z",
		ncx: "ncx",
		open_to_spread: false,
		orientation: "",
		package_doc_path: "/epub_content/israeli_sailing/OEPBS/content.opf",
		page_prog_dir: "rtl",
		paginate_backwards: false,
		pubdate: "2012-08-19",
		publisher: "אורי עידן",
		rights: "Creative commons 2.5 CC-BY-SA",
		root_url: "epub_content/israeli_sailing/OEPBS/content.opf",
		spread: "",
		src_url: "Local Directory: israelsailing_20120909/",
		title: "מפליגים בישראל",
		updated_at: "2012-12-14T00:50:43.914Z"
	},

	{
		active_class: "",
		apple_fixed: false,
		author: "",
		cover_href: "/images/library/missing-cover-image.png",
		created_at: "2012-12-14T00:50:46.484Z",
		description: "",
		epub_version: "3.0",
		file_path: "epub_content/character_1/OPS/package.opf",
		fixed_layout: true,
		id: "urn:uuid:ACA8C671-6C1F-1014-8433-7416564D7508",
		key: "character_1",
		language: "ja-jp",
		layout: "pre-paginated",
		modified_date: "2012-08-14T13:54:00Z",
		ncx: "ncxtoc",
		open_to_spread: false,
		orientation: "portrait",
		package_doc_path: "/epub_content/character_1/OPS/package.opf",
		page_prog_dir: "rtl",
		paginate_backwards: false,
		pubdate: "",
		publisher: "",
		rights: "",
		root_url: "epub_content/character_1/OPS/package.opf",
		spread: "landscape",
		src_url: "Local Directory: haruko-jpeg-20120814/",
		title: "ハルコさんの彼氏",
		updated_at: "2012-12-14T00:50:58.638Z"
	},

	{
		active_class: "",
		apple_fixed: false,
		author: "",
		cover_href: "/images/library/missing-cover-image.png",
		created_at: "2012-12-14T00:51:01.509Z",
		description: "",
		epub_version: "3.0",
		file_path: "epub_content/character_2/OPS/package.opf",
		fixed_layout: true,
		id: "urn:uuid:A649F639-6C1F-1014-8CC3-F813564D7508",
		key: "character_2",
		language: "ja-jp",
		layout: "pre-paginated",
		modified_date: "2012-05-24T00:00:00Z",
		ncx: "ncxtoc",
		open_to_spread: false,
		orientation: "portrait",
		package_doc_path: "/epub_content/character_2/OPS/package.opf",
		page_prog_dir: "rtl",
		paginate_backwards: false,
		pubdate: "",
		publisher: "",
		rights: "",
		root_url: "epub_content/character_2/OPS/package.opf",
		spread: "landscape",
		src_url: "Local Directory: haruko-html-jpeg-20120524 (1)/",
		title: "ハルコさんの彼氏",
		updated_at: "2012-12-14T00:51:15.601Z"
	},

	{
		active_class: "",
		apple_fixed: false,
		author: "EPUB 3 Working Group",
		cover_href: "epub_content/epub_spec30_2/EPUB/img/epub_logo_color.jpg",
		created_at: "2012-12-14T00:51:18.274Z",
		description: "",
		epub_version: "3.0",
		file_path: "epub_content/epub_spec30_2/EPUB/package.opf",
		fixed_layout: false,
		id: "code.google.com.epub-samples.epub30-spec",
		key: "epub_spec30_2",
		language: "en",
		layout: "",
		modified_date: "2012-02-27T16:38:35Z",
		ncx: "",
		open_to_spread: false,
		orientation: "",
		package_doc_path: "/epub_content/epub_spec30_2/EPUB/package.opf",
		page_prog_dir: "",
		paginate_backwards: false,
		pubdate: "",
		publisher: "",
		rights: "",
		root_url: "epub_content/epub_spec30_2/EPUB/package.opf",
		spread: "",
		src_url: "Local Directory: epub30-spec-20121128/",
		title: "EPUB 3.0 Specification",
		updated_at: "2012-12-14T00:51:31.151Z"
	},

	{
		active_class: "",
		apple_fixed: false,
		author: "Collectif",
		cover_href: "epub_content/guide_hachette/EPUB/Image/cover.jpg",
		created_at: "2012-12-14T00:51:34.071Z",
		description: "",
		epub_version: "3.0",
		file_path: "epub_content/guide_hachette/EPUB/content.opf",
		fixed_layout: false,
		id: "code.google.com.epub-samples.guide-des-vins_header-and-footer",
		key: "guide_hachette",
		language: "fr",
		layout: "",
		modified_date: "2012-10-02T18:00:00Z",
		ncx: "",
		open_to_spread: false,
		orientation: "",
		package_doc_path: "/epub_content/guide_hachette/EPUB/content.opf",
		page_prog_dir: "",
		paginate_backwards: false,
		pubdate: "2010",
		publisher: "Hachette Pratique",
		rights: "This work is shared with the public using the Attribution-ShareAlike 3.0 Unported (CC BY-SA 3.0) license.",
		root_url: "epub_content/guide_hachette/EPUB/content.opf",
		spread: "",
		src_url: "Local Directory: GhV-oeb-page-20121015/",
		title: "Guide Hachette des Vins 2011",
		updated_at: "2012-12-14T00:52:11.119Z"
	},

// Original data

	// {
	// 	"fixed_layout":false,
	// 	"open_to_spread":false,
	// 	"cover_href":"/images/library/missing-cover-image.png",
	// 	"created_at":"2012-03-27T19:22:01.521Z",
	// 	"updated_at":"2012-03-27T19:23:38.309Z",
	// 	"key":"1",
	// 	"src_url":"http://code.google.com/p/epub-samples/downloads/list",
	// 	"package_doc_path":"/epub_content/1/EPUB/package.opf",
	// 	"id":"code.google.com.epub-samples.linear-algebra",
	// 	"epub_version":"3.0",
	// 	"title":"A First Course in Linear Algebra",
	// 	"author":"Robert A. Beezer",
	// 	"publisher":"",
	// 	"description":"",
	// 	"rights":"This work is shared with the public using the GNU Free Documentation License, Version 1.2.",
	// 	"language":"en",
	// 	"pubdate":"",
	// 	"modified_date":"2012-03-05T12:47:00Z",
	// 	"layout":"",
	// 	"spread":"",
	// 	"orientation":"",
	// 	"ncx":""
	// },
	// {
	// 	"fixed_layout":false,
	// 	"open_to_spread":false,
	// 	"cover_href":"/epub_content/2/EPUB/images/portrait.jpg",
	// 	"created_at":"2012-03-27T19:24:45.543Z",
	// 	"updated_at":"2012-03-27T19:25:00.094Z",
	// 	"key":"2",
	// 	"src_url":"http://code.google.com/p/epub-samples/downloads/list",
	// 	"package_doc_path":"/epub_content/2/EPUB/cole.opf",
	// 	"id":"code.google.com.epub-samples.cole-voyage-of-life",
	// 	"epub_version":"3.0",
	// 	"title":"Thomas Cole - The Voyage of Life",
	// 	"author":"Jesse Dylan",
	// 	"publisher":"",
	// 	"description":"",
	// 	"rights":"This work is licensed under a Creative Commons Attribution-ShareAlike 3.0 Unported License.",
	// 	"language":"en-US",
	// 	"pubdate":"",
	// 	"modified_date":"2012-03-20T11:37:00Z",
	// 	"layout":"",
	// 	"spread":"",
	// 	"orientation":"",
	// 	"ncx":""
	// },{
	// 	"fixed_layout":false,
	// 	"open_to_spread":false,
	// 	"cover_href":"/epub_content/3/EPUB/wasteland-cover.jpg",
	// 	"created_at":"2012-03-27T19:25:40.235Z",
	// 	"updated_at":"2012-03-27T19:26:06.326Z",
	// 	"key":"3",
	// 	"src_url":"http://code.google.com/p/epub-samples/downloads/list",
	// 	"package_doc_path":"/epub_content/3/EPUB/wasteland.opf",
	// 	"id":"code.google.com.epub-samples.wasteland-basic","epub_version":"3.0",
	// 	"title":"The Waste Land","author":"T.S. Eliot",
	// 	"publisher":"",
	// 	"description":"",
	// 	"rights":"This work is shared with the public using the Attribution-ShareAlike 3.0 Unported (CC BY-SA 3.0) license.",
	// 	"language":"en-US",
	// 	"pubdate":"2011-09-01",
	// 	"modified_date":"2012-01-18T12:47:00Z",
	// 	"layout":"",
	// 	"spread":"",
	// 	"orientation":"",
	// 	"ncx":"ncx"
	// },{
	// 	"fixed_layout":true,
	// 	"open_to_spread":false,
	// 	"cover_href":"/epub_content/4/EPUB/Image/cover.jpg",
	// 	"created_at":"2012-03-28T18:24:18.450Z",
	// 	"updated_at":"2012-03-28T18:25:32.553Z",
	// 	"key":"4",
	// 	"src_url":"http://code.google.com/p/epub-samples/downloads/list",
	// 	"package_doc_path":"/epub_content/4/EPUB/package.opf",
	// 	"id":"urn:uuid:d5803940-647f-11e1-ad77-0002a5d5c51b",
	// 	"epub_version":"3.0",
	// 	"title":"Page Blanche","author":"Boulet",
	// 	"publisher":"éditions Delcourt",
	// 	"description":"",
	// 	"rights":"This work is shared with the public using the Attribution-ShareAlike 3.0 Unported (CC BY-SA 3.0) license.",
	// 	"language":"fr",
	// 	"pubdate":"2012-01-18",
	// 	"modified_date":"2012-03-06T12:00:00Z",
	// 	"layout":"pre-paginated",
	// 	"spread":"auto",
	// 	"orientation":"auto",
	// 	"ncx":""
	// }, {
	// 	"author": "Mary Webb",
	// 	"cover_href": "/images/library/missing-cover-image.png",
	// 	"created_at": "2012-04-10T21:47:53.353Z",
	// 	"description": "",
	// 	"epub_version": "2.0",
	// 	"fixed_layout": false,
	// 	"id": "urn:uuid:ADDB2B4D-BA43-4DE9-8BAB-CF8759C8F843",
	// 	"key": "3921047c34132ab12338059f09bbf5c8",
	// 	"language": "en-gb",
	// 	"layout": "",
	// 	"modified_date": "",
	// 	"ncx": "ncx",
	// 	"open_to_spread": false,
	// 	"orientation": "",
	// 	"package_doc_path": "/epub_content/5/OPS/content.opf",
	// 	"pubdate": "2002",
	// 	"publisher": "epubBooks (www.epubbooks.com)",
	// 	"rights": "↵            Provided for free by epubBooks.com. Not for commercial use.↵            This EPUB eBook is released under a Creative Commons (BY-NC-ND/3.0) Licence.↵            Source text and images are in the Public Domain.↵      ",
	// 	"spread": "",
	// 	"src_url": "webb-precious-bane.epub",
	// 	"title": "Precious Bane",
	// 	"updated_at": "2012-04-10T21:48:57.267Z"
	// }, {
	// 	"apple_fixed": false,
	// 	"author": "EPUB 3 Working Group",
	// 	"cover_href": "/epub_content/epub30_spec/EPUB/img/epub_logo_color.jpg",
	// 	"created_at": "2012-06-15T00:05:56.371Z",
	// 	"description": "",
	// 	"epub_version": "3.0",
	// 	"fixed_layout": false,
	// 	"id": "code.google.com.epub-samples.epub30-spec",
	// 	"key": "epub30_spec",
	// 	"language": "en",
	// 	"layout": "",
	// 	"modified_date": "2012-02-27T16:38:35Z",
	// 	"ncx": "",
	// 	"open_to_spread": false,
	// 	"orientation": "",
	// 	"package_doc_path": "/epub_content/epub30_spec/EPUB/package.opf",
	// 	"page_prog_dir": "",
	// 	"paginate_backwards": false,
	// 	"pubdate": "",
	// 	"publisher": "",
	// 	"rights": "",
	// 	"spread": "",
	// 	"src_url": "http://code.google.com/p/epub-samples/downloads/list",
	// 	"title": "EPUB 3.0 Specification",
	// 	"updated_at": "2012-06-15T00:06:37.334Z"
	// }, {
	// 	"apple_fixed": false,
	// 	"author": "",
	// 	"cover_href": "/images/library/missing-cover-image.png",
	// 	"created_at": "2012-06-15T00:05:56.371Z",
	// 	"description": "",
	// 	"epub_version": "3.0",
	// 	"fixed_layout": false,
	// 	"id": "http://www.aozora.gr.jp/cards/000148/card776.html",
	// 	"key": "kusamakura",
	// 	"language": "ja-jp",
	// 	"layout": "",
	// 	"modified_date": "2012-04-24T00:00:00Z",
	// 	"ncx": "ncxtoc",
	// 	"open_to_spread": false,
	// 	"orientation": "",
	// 	"package_doc_path": "/epub_content/kusamakura/OPS/package.opf",
	// 	"page_prog_dir": "rtl",
	// 	"paginate_backwards": false,
	// 	"pubdate": "",
	// 	"publisher": "",
	// 	"rights": "",
	// 	"spread": "",
	// 	"src_url": "http://code.google.com/p/epub-samples/downloads/list",
	// 	"title": "草枕",
	// 	"updated_at": "2012-06-15T00:06:55.212Z"
	// }, {
	// 	"apple_fixed": false,
	// 	"author": "Herman Melville",
	// 	"cover_href": "/epub_content/moby_dick/OPS/images/9780316000000.jpg",
	// 	"created_at": "2012-06-15T00:05:56.371Z",
	// 	"description": "",
	// 	"epub_version": "3.0",
	// 	"fixed_layout": false,
	// 	"id": "code.google.com.epub-samples.moby-dick-basic",
	// 	"key": "moby_dick",
	// 	"language": "en-US",
	// 	"layout": "",
	// 	"modified_date": "2012-01-18T12:47:00Z",
	// 	"ncx": "",
	// 	"open_to_spread": false,
	// 	"orientation": "",
	// 	"package_doc_path": "/epub_content/moby_dick/OPS/package.opf",
	// 	"page_prog_dir": "",
	// 	"paginate_backwards": false,
	// 	"pubdate": "",
	// 	"publisher": "Harper & Brothers, Publishers",
	// 	"rights": "This work is shared with the public using the Attribution-ShareAlike 3.0 Unported (CC BY-SA 3.0) license.",
	// 	"spread": "",
	// 	"src_url": "http://code.google.com/p/epub-samples/downloads/list",
	// 	"title": "Moby-Dick",
	// 	"updated_at": "2012-06-15T00:07:21.516Z"
	// }, {
	// 	"apple_fixed": false,
	// 	"author": "",
	// 	"cover_href": "/epub_content/trees/EPUB/cover.jpg",
	// 	"created_at": "2012-06-15T00:05:56.371Z",
	// 	"description": "Test of canvas element and CSS3 multi-column layout",
	// 	"epub_version": "3.0",
	// 	"fixed_layout": false,
	// 	"id": "code.google.com.epub-samples.trees",
	// 	"key": "trees",
	// 	"language": "en",
	// 	"layout": "",
	// 	"modified_date": "2012-04-05T12:47:00Z",
	// 	"ncx": "",
	// 	"open_to_spread": false,
	// 	"orientation": "",
	// 	"package_doc_path": "/epub_content/trees/EPUB/package.opf",
	// 	"page_prog_dir": "",
	// 	"paginate_backwards": false,
	// 	"pubdate": "",
	// 	"publisher": "",
	// 	"rights": "",
	// 	"spread": "",
	// 	"src_url": "http://code.google.com/p/epub-samples/downloads/list",
	// 	"title": "Trees",
	// 	"updated_at": "2012-06-15T00:07:49.803Z"
	// }, {
	// 	"apple_fixed": false,
	// 	"author": "",
	// 	"cover_href": "/images/library/missing-cover-image.png",
	// 	"created_at": "2012-06-15T00:08:27.336Z",
	// 	"description": "",
	// 	"epub_version": "3.0",
	// 	"fixed_layout": true,
	// 	"id": "urn:uuid:A649F639-6C1F-1014-8CC3-F813564D7508",
	// 	"key": "haruko",
	// 	"language": "ja-jp",
	// 	"layout": "pre-paginated",
	// 	"modified_date": "2012-05-24T00:00:00Z",
	// 	"ncx": "ncxtoc",
	// 	"open_to_spread": false,
	// 	"orientation": "portrait",
	// 	"package_doc_path": "/epub_content/haruko/OPS/package.opf",
	// 	"page_prog_dir": "rtl",
	// 	"paginate_backwards": false,
	// 	"pubdate": "",
	// 	"publisher": "",
	// 	"rights": "",
	// 	"spread": "landscape",
	// 	"src_url": "http://code.google.com/p/epub-samples/downloads/list",
	// 	"title": "ハルコさんの彼氏",
	// 	"updated_at": "2012-06-15T00:08:36.776Z"
	// }, {
	// 	"apple_fixed": false,
	// 	"author": "",
	// 	"cover_href": "/images/library/missing-cover-image.png",
	// 	"created_at": "2012-06-15T00:08:27.336Z",
	// 	"description": "",
	// 	"epub_version": "3.0",
	// 	"fixed_layout": false,
	// 	"id": "code.google.com.epub-samples.hefty.water",
	// 	"key": "hefty_water",
	// 	"language": "en",
	// 	"layout": "",
	// 	"modified_date": "2012-03-29T12:00:00Z",
	// 	"ncx": "",
	// 	"open_to_spread": false,
	// 	"orientation": "",
	// 	"package_doc_path": "/epub_content/hefty_water/EPUB/package.opf",
	// 	"page_prog_dir": "",
	// 	"paginate_backwards": false,
	// 	"pubdate": "2012-03-29",
	// 	"publisher": "",
	// 	"rights": "",
	// 	"spread": "",
	// 	"src_url": "http://code.google.com/p/epub-samples/downloads/list",
	// 	"title": "Hefty Water",
	// 	"updated_at": "2012-06-15T00:09:37.681Z"
	// }, {
	// 	"apple_fixed": false,
	// 	"author": "Matt Garrish",
	// 	"cover_href": "/epub_content/accessible_epub_3/EPUB/covers/9781449328030_lrg.jpg",
	// 	"created_at": "2012-06-15T00:10:25.327Z",
	// 	"current_margin": 1,
	// 	"current_theme": "default-theme",
	// 	"description": "",
	// 	"epub_version": "3.0",
	// 	"fixed_layout": false,
	// 	"font_size": 10,
	// 	"id": "urn:isbn:9781449328030",
	// 	"key": "accessible_epub_3",
	// 	"language": "en",
	// 	"layout": "",
	// 	"modified_date": "2012-02-20T22:17:24Z",
	// 	"ncx": "ncx",
	// 	"open_to_spread": false,
	// 	"orientation": "",
	// 	"package_doc_path": "/epub_content/accessible_epub_3/EPUB/package.opf",
	// 	"page_prog_dir": "",
	// 	"paginate_backwards": false,
	// 	"pubdate": "2012",
	// 	"publisher": "O’Reilly Media, Inc.",
	// 	"rights": "Copyright © 2012 O’Reilly Media, Inc",
	// 	"spread": "",
	// 	"src_url": "http://code.google.com/p/epub-samples/downloads/list",
	// 	"title": "Accessible EPUB 3",
	// 	"two_up": true,
	// 	"updated_at": "2012-06-15T00:13:26.319Z"
	// }, {
	// 	"apple_fixed": false,
	// 	"author": "Pr David Khayat",
	// 	"cover_href": "/epub_content/regime_anticancer_arabic/EPUB/Image/cover.jpg",
	// 	"created_at": "2012-06-15T00:11:17.450Z",
	// 	"description": "",
	// 	"epub_version": "3.0",
	// 	"fixed_layout": false,
	// 	"id": "code.google.com.epub-samples.regime-anticancer-arabic",
	// 	"key": "regime_anticancer_arabic",
	// 	"language": "ar",
	// 	"layout": "",
	// 	"modified_date": "2012-03-26T12:00:00Z",
	// 	"ncx": "ncx",
	// 	"open_to_spread": false,
	// 	"orientation": "",
	// 	"package_doc_path": "/epub_content/regime_anticancer_arabic/EPUB/package.opf",
	// 	"page_prog_dir": "rtl",
	// 	"paginate_backwards": false,
	// 	"pubdate": "2012",
	// 	"publisher": "Hachette Antoine",
	// 	"rights": "This work is shared with the public using the Attribution-ShareAlike 3.0 Unported (CC BY-SA 3.0) license.",
	// 	"spread": "",
	// 	"src_url": "http://code.google.com/p/epub-samples/downloads/list",
	// 	"title": "Le Vrai Régime anti-cancer",
	// 	"updated_at": "2012-06-15T00:11:57.065Z"
	// }
]